import Link from 'next/link';
import '../../src/styles/pages.css';

export const metadata = {
  title: 'Privacy Policy',
  description:
    'How Cromis Digital collects, uses, and protects information from visitors of cromisdigital.com.',
};

export default function PrivacyPage() {
  return (
    <main>
      <div className="page-hero">
        <div className="container">
          <span className="section-label">Legal</span>
          <h1>Privacy Policy</h1>
          <p>How we handle the information you share with us.</p>
          <p className="legal-meta">Effective date: June 16, 2026</p>
        </div>
      </div>

      <section className="legal-page">
        <div className="container">
          <div className="legal-notice">
            <strong>Template notice.</strong> This policy is a reasonable starting
            point for a small Florida service business website. It is not legal
            advice. Have it reviewed by an attorney, or replace it with a policy
            generated by a service like Termly or iubenda, before relying on it
            for compliance.
          </div>

          <div className="legal-content">
            <h2>1. Who we are</h2>
            <p>
              This Privacy Policy describes how Cromis Digital (&ldquo;Cromis
              Digital,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) collects, uses,
              and shares information when you visit cromisdigital.com (the
              &ldquo;Site&rdquo;) or contact us through it. Cromis Digital is
              owned and operated by Trey Holland and is based in Old Town,
              Florida.
            </p>

            <h2>2. Information we collect</h2>
            <h3>Information you give us</h3>
            <ul>
              <li>
                <strong>Contact form submissions:</strong> when you fill out the
                form on our Contact page, we collect the name, business name,
                phone number, email address, the service category you select,
                and any message you provide.
              </li>
              <li>
                <strong>Direct communication:</strong> if you email or call us,
                we receive whatever you choose to share.
              </li>
            </ul>

            <h3>Information collected automatically</h3>
            <p>
              The Site does not currently use analytics, advertising, or
              behavioral tracking cookies. Our hosting provider may keep standard
              server logs (IP address, browser type, pages requested, timestamps)
              for security and operational purposes. If we add analytics in the
              future, we will update this policy.
            </p>
            <p>
              The Site loads the Inter font from Google Fonts. When your browser
              requests the font, Google receives standard request information
              such as your IP address. Google&rsquo;s use of that data is
              governed by{' '}
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Google&rsquo;s privacy policy
              </a>
              . We are evaluating self-hosting the font to remove this
              third-party request.
            </p>

            <h2>3. How we use information</h2>
            <ul>
              <li>To respond to your inquiries and provide services you request.</li>
              <li>To send communications you have asked for.</li>
              <li>To operate, maintain, and secure the Site.</li>
              <li>To comply with legal obligations.</li>
            </ul>

            <h2>4. How we share information</h2>
            <p>We do not sell your personal information. We share it only with:</p>
            <ul>
              <li>
                <strong>Service providers</strong> who help us run the Site or
                process inquiries — for example, our contact-form processor
                (Web3Forms) and our hosting provider (Vercel). These providers
                are bound by their own privacy practices and only process
                information on our behalf.
              </li>
              <li>
                <strong>Legal and safety reasons</strong> — to comply with the
                law, enforce our Terms, or protect rights, property, or safety.
              </li>
              <li>
                <strong>Business transfers</strong> — in connection with a
                merger, acquisition, or sale of assets, where information may be
                transferred subject to this Policy.
              </li>
            </ul>

            <h2>5. Data retention</h2>
            <p>
              We keep information for as long as needed to respond to your
              inquiry, deliver services, and meet legal or operational
              requirements, then we delete it. You can ask us to delete your
              information at any time.
            </p>

            <h2>6. Your choices</h2>
            <p>
              You can opt out of further communications from us by replying to
              the message and telling us. You can ask us to access, correct, or
              delete the information you have shared by contacting us at the
              address below.
            </p>

            <h2>7. California Notice at Collection</h2>
            <p>
              If you are a California resident, the California Consumer Privacy
              Act (CCPA) gives you specific rights. The categories of personal
              information we collect, the purposes for which we use them, and
              our retention practices are described above.
            </p>
            <ul>
              <li>
                <strong>Categories collected:</strong> identifiers (name, email,
                phone), commercial information (your inquiry and stated needs),
                and internet or network activity (server logs).
              </li>
              <li>
                <strong>Purposes:</strong> to communicate with you, provide
                services, and operate and secure the Site.
              </li>
              <li>
                <strong>Sale or sharing for cross-context behavioral
                advertising:</strong> we do not sell or share personal information
                for cross-context behavioral advertising.
              </li>
              <li>
                <strong>Your rights:</strong> you may request to know, delete,
                or correct your information; opt out of sale or sharing (we do
                not engage in either); limit use of sensitive personal
                information; and not be discriminated against for exercising
                these rights.
              </li>
              <li>
                <strong>To exercise these rights:</strong> email{' '}
                <a href="mailto:TreyHolland@cromisdigital.com">
                  TreyHolland@cromisdigital.com
                </a>
                . We will verify your request using the information you provide.
              </li>
            </ul>

            <h2>8. Cookies</h2>
            <p>
              The Site does not currently use tracking cookies. Your browser may
              store small files needed for the Site to function. If we add
              optional cookies (for example, analytics) in the future, we will
              update this policy and, where required, provide a way for you to
              consent or opt out.
            </p>

            <h2>9. Children&rsquo;s privacy</h2>
            <p>
              The Site is not directed to children under 13, and we do not
              knowingly collect personal information from them. If you believe a
              child has provided us information, contact us and we will delete
              it.
            </p>

            <h2>10. Security</h2>
            <p>
              We use reasonable administrative and technical safeguards to
              protect the information you share with us. No method of
              transmission over the internet is fully secure, however, and we
              cannot guarantee absolute security.
            </p>

            <h2>11. Changes to this policy</h2>
            <p>
              We may update this policy from time to time. When we do, we will
              update the effective date above. Material changes will be
              communicated through the Site.
            </p>

            <h2>12. Contact us</h2>
            <p>
              Questions about this policy? Reach out:
            </p>
            <ul>
              <li>Cromis Digital, Old Town, Florida</li>
              <li>
                Email:{' '}
                <a href="mailto:TreyHolland@cromisdigital.com">
                  TreyHolland@cromisdigital.com
                </a>
              </li>
              <li>
                Phone: <a href="tel:+13529497355">(352) 949-7355</a>
              </li>
              <li>
                <Link href="/contact">Use the contact form</Link>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </main>
  );
}
