import Link from 'next/link';
import '../../src/styles/pages.css';

export const metadata = {
  title: 'Terms of Service',
  description:
    'The terms that govern your use of cromisdigital.com and any services provided by Cromis Digital.',
};

export default function TermsPage() {
  return (
    <main>
      <div className="page-hero">
        <div className="container">
          <span className="section-label">Legal</span>
          <h1>Terms of Service</h1>
          <p>The rules of the road for using this site and working with us.</p>
          <p className="legal-meta">Effective date: June 16, 2026</p>
        </div>
      </div>

      <section className="legal-page">
        <div className="container">
          <div className="legal-notice">
            <strong>Template notice.</strong> These terms are a reasonable
            starting point for a small Florida service business website. They
            are not legal advice. Have them reviewed by an attorney, or replace
            them with terms generated by a service like Termly or iubenda,
            before relying on them.
          </div>

          <div className="legal-content">
            <h2>1. Acceptance of these terms</h2>
            <p>
              By accessing or using cromisdigital.com (the &ldquo;Site&rdquo;)
              you agree to these Terms of Service (&ldquo;Terms&rdquo;). If you
              do not agree, do not use the Site.
            </p>

            <h2>2. Who we are</h2>
            <p>
              The Site is operated by Cromis Digital (&ldquo;Cromis
              Digital,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;), owned and
              operated by Trey Holland and based in Old Town, Florida.
            </p>

            <h2>3. Use of the Site</h2>
            <p>You agree to use the Site lawfully and to not:</p>
            <ul>
              <li>
                Access, scrape, or copy the Site or its content using automated
                means without our written permission.
              </li>
              <li>
                Attempt to interfere with the Site&rsquo;s operation, security,
                or other users&rsquo; use of it.
              </li>
              <li>
                Reverse engineer, decompile, or otherwise try to extract source
                code from the Site.
              </li>
              <li>Use the Site to send unsolicited messages or for any unlawful purpose.</li>
            </ul>

            <h2>4. Services and engagements</h2>
            <p>
              Information on the Site about our services is for general
              information only. Any actual engagement to provide services
              (website builds, AI lead systems, local SEO, or other work) is
              governed by a separate written agreement between Cromis Digital
              and the client. Nothing on this Site creates a binding offer or
              client relationship.
            </p>

            <h2>5. Intellectual property</h2>
            <p>
              The Site, including its design, code, copy, images, and the
              Cromis Digital name and logo, is owned by Cromis Digital and
              protected by intellectual property laws. You may not copy, modify,
              or distribute any part of the Site without our written
              permission, except as needed to view and use the Site normally.
            </p>
            <p>
              Third-party names, logos, and screenshots that appear on the Site
              (for example, client showcases) are the property of their
              respective owners and are used to identify their businesses or
              with their permission.
            </p>

            <h2>6. Form submissions and communications</h2>
            <p>
              When you submit information through the contact form, email us,
              or call us, you give us permission to use that information to
              respond to you and to provide the services you ask about, in
              accordance with our{' '}
              <Link href="/privacy">Privacy Policy</Link>.
            </p>

            <h2>7. Third-party links</h2>
            <p>
              The Site may link to third-party websites we do not control. We
              are not responsible for the content, policies, or practices of
              those sites. Following such links is at your own risk.
            </p>

            <h2>8. Disclaimers</h2>
            <p>
              The Site is provided &ldquo;as is&rdquo; and &ldquo;as
              available.&rdquo; To the maximum extent permitted by law, Cromis
              Digital disclaims all warranties, express or implied, including
              warranties of merchantability, fitness for a particular purpose,
              and non-infringement. We do not warrant that the Site will be
              uninterrupted, error-free, or free of harmful components.
            </p>

            <h2>9. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Cromis Digital will not
              be liable for any indirect, incidental, special, consequential,
              or punitive damages, or for any loss of profits or revenues,
              arising out of or relating to your use of the Site. Our total
              liability for any claim relating to the Site will not exceed one
              hundred U.S. dollars (US&nbsp;$100).
            </p>

            <h2>10. Indemnification</h2>
            <p>
              You agree to indemnify and hold Cromis Digital harmless from any
              claim or demand arising out of your misuse of the Site or your
              violation of these Terms.
            </p>

            <h2>11. Termination</h2>
            <p>
              We may suspend or terminate your access to the Site at any time,
              with or without notice, if we believe you have violated these
              Terms or for any other reason.
            </p>

            <h2>12. Governing law and venue</h2>
            <p>
              These Terms are governed by the laws of the State of Florida,
              without regard to its conflict-of-laws principles. Any dispute
              relating to the Site or these Terms will be resolved in the state
              or federal courts located in Florida, and you consent to that
              jurisdiction and venue.
            </p>

            <h2>13. Changes to these Terms</h2>
            <p>
              We may update these Terms from time to time. When we do, we will
              update the effective date above. Continued use of the Site after
              changes means you accept the updated Terms.
            </p>

            <h2>14. Contact us</h2>
            <ul>
              <li>Cromis Digital, Old Town, Florida</li>
              <li>
                Email:{' '}
                <a href="mailto:TreyHolland@cromisdigital.com">
                  TreyHolland@cromisdigital.com
                </a>
              </li>
              <li>
                Phone: <a href="tel:+13529497355">(352) 949-7355</a>
              </li>
              <li>
                <Link href="/contact">Use the contact form</Link>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </main>
  );
}
